stages:
  - build
  - plan
  - deploy
  - k8s_deploy
  - observe

variables:
  AWS_ROLE_ARN: arn:aws:iam::510674263883:role/GitLabPipelineRole
  AWS_REGION: ap-south-1
  LOCAL_TAG: "local-macos"



build_images:
  stage: build
  tags:
    - local-macos
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/worker:latest .
    - docker push $CI_REGISTRY_IMAGE/worker:latest

plan_infra:
  stage: plan
  tags:
    - local-macos
  script:
    - cd infra
    - terraform init -reconfigure
    - terraform plan -out=plan.cache

apply_infra:
  stage: deploy
  tags:
    - local-macos
  script:
    - cd infra
    - |
      CREDENTIALS=$(aws sts assume-role \
        --role-arn "arn:aws:iam::510674263883:role/GitLabPipelineRole" \
        --role-session-name "GitLabLocalRunner" \
        --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
        --output text)
    - export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | cut -d' ' -f1)
    - export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | cut -d' ' -f2)
    - export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | cut -d' ' -f3)
    
    
    - terraform init -reconfigure
    - terraform apply -auto-approve plan.cache
    - echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" > ../deploy.env
  artifacts:
    reports:
      dotenv: deploy.env

configure_networking:
  stage: deploy
  tags:
    - local-macos
  image: alpine:latest
  needs: [apply_infra]
  before_script:
    - apk add --update openssh-client
  script:
    
    - |
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
        echo "Waiting for EC2 boot script (cloud-init) to finish..."
        until [ -f /var/lib/cloud/instance/boot-finished ]; do
          sleep 5
          echo -n "."
        done
        echo "Ready!"
        
        MINIKUBE_IP=$(minikube ip)
        sudo iptables -t nat -A PREROUTING -p tcp --dport 31379 -j DNAT --to-destination $MINIKUBE_IP:31379
        sudo iptables -I FORWARD 1 -d $MINIKUBE_IP -p tcp --dport 31379 -j ACCEPT
        
        sudo apt-get update && sudo apt-get install -y iptables-persistent
        sudo netfilter-persistent save
      EOF

deploy_pods:
  stage: k8s_deploy
  tags:
    - local-macos
  needs: [apply_infra, configure_networking]
  script:
    - scp -o StrictHostKeyChecking=no -r k8s/ ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/
    - |
      ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
        helm upgrade --install redis-exporter prometheus-community/prometheus-redis-exporter \
          --set redisAddress=redis-service.default.svc.cluster.local:6379
        
        # Apply your ServiceMonitor and Dashboard ConfigMap so they don't vanish on restart
        minikube kubectl -- apply -f /home/ubuntu/k8s/service-monitor.yaml
        minikube kubectl -- apply -f /home/ubuntu/k8s/grafana-dashboard-cm.yaml
      EOF

observe_cluster:
  stage: observe
  tags:
    - local-macos
  image: alpine:latest
  needs:
    - job: apply_infra
      artifacts: true
    - job: deploy_pods
  before_script:
    - apk add --update openssh-client
    - cat "$SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/id_rsa
    - echo "" >> /tmp/id_rsa
    - chmod 400 /tmp/id_rsa

  script:
    - |
      ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
        
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        
        
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring --create-namespace \
          --set grafana.adminPassword=admin
        
        
        minikube kubectl -- apply -f /home/ubuntu/k8s/service-monitor.yaml
        
        
        minikube kubectl -- rollout status deployment/prometheus-grafana -n monitoring
      EOF