apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: chaos-scaler
spec:
  scaleTargetRef:
    name: chaos-worker        
  minReplicaCount: 1          
  maxReplicaCount: 10         
  triggers:
  - type: redis
    metadata:
      address: redis-service.default.svc.cluster.local:6379
      listName: chaos_tasks   
      listLength: "5"         