apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-monitor
  namespace: monitoring
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-redis-exporter
      app.kubernetes.io/instance: redis-exporter
  endpoints:
  - port: 9121
    interval: 5s # High-frequency scraping for chaos tracking